apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/www/html
          name: html-volume
  volumes:
    - name: html-volume
      hostPath:
        path: /var/www/html
        type: DirectoryOrCreate
